export const decorImagesData = [
  {
    name: "ribbon",
    top: "45vh",
    left: "80vw",
    phoneTop: "10vh",
    phoneLeft: "30vw",
    height: "200px",
    width: "200px",
    display: "none",
  },
  {
    name: "ribbon",
    top: "65vh",
    left: "20vw",
    phoneTop: "5vh",
    phoneLeft: "0vw",
    height: "100px",
    width: "100px",
    display: "none",
  },
  {
    name: "white-love",
    top: "80vh",
    left: "0vw",
    phoneTop: "80vh",
    phoneLeft: "-20vw",
    height: "200px",
    width: "200px",
  },
  {
    name: "rose-single",
    top: "-5vh",
    left: "20vw",
    phoneTop: "-10vh",
    phoneLeft: "40vw",
    height: "150px",
    width: "150px",
  },
  {
    name: "rose-single",
    top: "-5vh",
    left: "20vw",
    phoneTop: "77vh",
    phoneLeft: "0vw",
    height: "150px",
    width: "150px",
    display: "none",
  },
  {
    name: "rose-single",
    top: "27vh",
    left: "64vw",
    phoneTop: "77vh",
    phoneLeft: "0vw",
    height: "75px",
    width: "75px",
    display: "none",
  },
  {
    name: "red-love",
    top: "-5vh",
    left: "60vw",
    phoneTop: "20vh",
    phoneLeft: "70vw",
    height: "200px",
    width: "200px",
  },
  {
    name: "rose-double",
    top: "77vh",
    left: "88vw",
    phoneTop: "70vh",
    phoneLeft: "52vw",
    height: "300px",
    width: "300px",
  },
  {
    name: "circle",
    top: "15vh",
    left: "10vw",
    phoneTop: "20vh",
    phoneLeft: "20vw",
    height: "20px",
    width: "20px",
  },
];
